buildscript {
    repositories {
        mavenCentral()
        jcenter()
        maven { name = "forge"; url = "https://maven.minecraftforge.net/" }
        maven { name = "sonatype"; url = "https://oss.sonatype.org/content/repositories/snapshots/" }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.1-SNAPSHOT'
    }
}

apply plugin: 'net.minecraftforge.gradle.forge'

version = "1.0.0"
group = "dev.oryvex.client"
archivesBaseName = "OryvexClient"

sourceCompatibility = targetCompatibility = '1.8'
compileJava.options.encoding = 'UTF-8'

minecraft {
    // Minecraft 1.8.8 + Forge. اگر نسخه Forge عوض شد فقط همین دو خط رو تغییر بده.
    version = "1.8.8-11.15.0.1655"
    runDir = "run"
    mappings = "stable_20"
}

processResources {
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version

    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version': project.version, 'mcversion': project.minecraft.version
    }
    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}
